name: Documentation

on:
  push:
    branches: [main]

permissions: {}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: nightly

      - name: Build Documentation
        run: cargo +nightly doc --all-features --no-deps --workspace --document-private-items

      - name: Prepare to publish
        run: ./scripts/prep_documentation.sh

      - name: Publish to Github Pages
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          branch: gh-pages
          folder: target/doc
          clean: true
          single-commit: true
