name: Rust CI

on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        rust: ['nightly', 'beta', 'stable', 'msrv']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Resolve version
        id: resolve_version
        run: echo "version=$(./scripts/resolve-toolchain-version.sh ${{matrix.rust}})" >> "${GITHUB_OUTPUT}"

      - name: Install ${{ steps.resolve_version.outputs.version }} toolchain
        if: matrix.rust == 'nightly'
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: ${{ steps.resolve_version.outputs.version }}
          components: miri rustfmt clippy

      - name: Install ${{ steps.resolve_version.outputs.version }} toolchain
        if: matrix.rust != 'nightly'
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de
        with:
          toolchain: ${{ steps.resolve_version.outputs.version }}
          components: rustfmt clippy

      - uses: taiki-e/install-action@94c31af3204a9f15ab40b35ad084410b905bbc73 # v2.87.17
        with:
          tool: cargo-binstall

      - name: Setup gungraun-runner and Valgrind
        uses: gungraun/setup-gungraun@62591572561bb2f4ed2ae300b8a8bea99ea8ddaf # v1.1.3


      - name: Run full test script
        run: ./scripts/full-test.sh "${STEPS_RESOLVE_VERSION_OUTPUTS_VERSION}"
        env:
          STEPS_RESOLVE_VERSION_OUTPUTS_VERSION: ${{ steps.resolve_version.outputs.version }}
